version: '3.8'

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb
    networks:
      - study_mate

  back-end:
    build: .
    container_name: study-mate
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
#      RABBIT_HOST: rabbitmq
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - study_mate

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.12.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command:
      - bash
      - -c
      - |
        rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-server
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

    networks:
      - study_mate

volumes:
  mariadb_data:

networks:
  study_mate:
    driver: bridge



