version: '3.8'

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb
    networks:
      - study_mate
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - study_mate

  back-end:
    build: .
    container_name: study-mate
    restart: always
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - study_mate

volumes:
  mariadb_data:

networks:
  study_mate:
    driver: bridge
