spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test # DB 접속 URL
    username: sa # DB 접속 username
    password: # DB 접속 password, 없음
    driver-class-name: org.h2.Driver # DB 접속 드라이버
  h2.console:
    enabled: true # 콘솔 사용 여부, 로컬에서 웹 브라우저로도 접속 가능
  jpa:
    hibernate:
      ddl-auto: create # 테이블을 자동으로 생성함
    properties:
      hibernate:
        format_sql: true # SQL 로그 출력
logging:
  level:
    org.hibernate.SQL: debug # SQL 로그 출력을 위한 로그 레벨 조정


